pipeline_template: jar/Jenkinsfile-auto-versioning-deployment
email_reply_to: argus-admin@salesforce.com
docker_test_images: dva/sfdc_centos7_jdk8
time_out_mins: 180
number_of_artifacts_to_keep: 3
compliance_required: false
build_pull_requests: true
pipeline_initial_build_number: 1
publish_jar: true