pipeline_template: rpm/Jenkinsfile-dva-yumrepo
email_reply_to: argus-admin@salesforce.com
time_out_mins: 180
number_of_artifacts_to_keep: 3
compliance_required: false
docker_test_images:
- dva/sfdc_rhel6_jdk8_mvn3.3.3
unit_tests_command: |-
  #mvn -DskipITs -DskipDockerBuild install
  #mvn jacoco:report
  #touch target/jacoco.exec
  #cat $(find ./ -name "jacoco.exec" -mindepth 3  -type f) >target/jacoco.exec
  mvn -DskipTests=true install -DskipDockerBuild
pipeline_initial_build_number: 84
docker_package_images:
- sfdc_rhel6_jdk8_rpmbuild
package_generation_command: "echo \"Creating users inside container...\"\nFILE=/tmp/project/SPECS/argus-webservices.spec\n\
  ORIG_USER=argus\nCUR_USER=`stat -c \"%U\" ${FILE}`\nCUR_UID=`stat -c \"%u\" ${FILE}`\n\
  CUR_GRP=`stat -c \"%G\" ${FILE}`\nCUR_GID=`stat -c \"%g\" ${FILE}`\necho \"Creating\
  \ users inside container...${CUR_USER} ${CUR_GRP} ${CUR_UID} ${CUR_GID}\"\n# In\
  \ some cases, there is user on the container that has a different name, but same\
  \ uid. \nif [[ ${CUR_GRP} == \"UNKNOWN\" ]]; then\n    echo \"Adding missing group...${ORIG_USER}\"\
  \n    groupadd --gid ${CUR_GID} ${ORIG_USER}\nfi\nif [[ ${CUR_USER} == \"UNKNOWN\"\
  \ ]]; then \n    echo \"Adding missing user...${ORIG_USER}\"\n    useradd --uid\
  \ ${CUR_UID} --gid ${CUR_GID} ${ORIG_USER}\n    CUR_USER=${ORIG_USER}\nfi\nif [[\
  \ ${CUR_USER} != ${ORIG_USER} ]]; then\n    uniq_uid=$((1 + $(cat /etc/passwd |\
  \ grep -v nobody | cut -f 3 -d: | sort -n | tail -n 1)))\n    usermod -l ${ORIG_USER}\
  \ ${CUR_USER}\nfi\nmake package"
package_repository: mandm
integration_tests_command: echo docker override
docker_image_name: argus2
